const AppAction = {
    LOADING_APP_START: 'LOADING_APP_START',
    CLOSE_LOADING_APP: 'CLOSE_LOADING_APP',
    LOADING_APP_POPUP_START: 'LOADING_APP_POPUP_START',
    CLOSE_LOADING_APP_POPUP: 'CLOSE_LOADING_APP_POPUP',

    FETCH_GET_CODE: 'FETCH_GET_CODE',
    FETCH_GET_CODE_SUCCESS: 'FETCH_GET_CODE_SUCCESS',
   
    

};

export default AppAction;
